# Site V1.0
name: "the site name" 
title: "the site name" 
description: "the site name" 
meta_description: "the site name" 
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: ''
#baseurl: 'https://mhwsample.co.uk.s3-website-eu-west-1.amazonaws.com'
#baseurl: 'https://s3-eu-west-1.amazonaws.com/mhwsample.co.uk/'
#C:\Users\GoldsmiD\documents\affiliates-jekyll-theme
email: 'goldsmithdallen@gmail.com'
#google_analytics: 'UA-46278016-1'
disqus: 'mhw'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  david:
    name: David
    display_name: David
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: 'goldsmithdallen@gmail.com'
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "Bio of David ."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge


destination: public 

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
