# Site V1.0
name: "Merley Neighbourhood Watch" 
title: "Merley Neighbourhood Watch"
description: "Merley Neighbourhood Watch"
meta_description: "Merley Neighbourhood Watch"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: ''
#baseurl: 'https://mhwsample.co.uk.s3-website-eu-west-1.amazonaws.com'
#baseurl: 'https://s3-eu-west-1.amazonaws.com/mhwsample.co.uk/'
#C:\Users\GoldsmiD\documents\affiliates-jekyll-theme
email: 'goldsmithdallen@gmail.com'
google_analytics: 'UA-46278016-1'
disqus: 'mhw'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  sal:
    name: Sal
    display_name: Sal
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: David
    display_name: David
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: 'goldsmithdallen@gmail.com'
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge